# Generated by Django 2.0.2 on 2018-02-16 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionpage', '0002_question_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='by_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='userpage.MyUser'),
        ),
    ]
