# Generated by Django 2.0.2 on 2018-02-16 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionpage', '0003_auto_20180216_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='by_user',
        ),
    ]
