# Generated by Django 2.0.2 on 2018-03-16 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionpage', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='answer_commented',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='questionpage.Answer'),
        ),
    ]
