# Generated by Django 2.0.2 on 2018-03-20 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionpage', '0010_auto_20180316_1822'),
        ('questionpage', '0009_auto_20180316_1508'),
    ]

    operations = [
    ]
