# Generated by Django 2.0.2 on 2018-03-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionpage', '0010_auto_20180316_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
