# Generated by Django 2.0.2 on 2018-03-20 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionpage', '0011_merge_20180319_2027'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
