# Generated by Django 2.0.2 on 2018-03-20 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionpage', '0013_auto_20180319_2107'),
        ('questionpage', '0011_question_tags'),
    ]

    operations = [
    ]
