# Generated by Django 2.0.2 on 2018-03-21 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionpage', '0014_merge_20180319_2244'),
        ('questionpage', '0014_merge_20180319_2253'),
    ]

    operations = [
    ]
