# Generated by Django 2.0.2 on 2018-03-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionpage', '0016_auto_20180321_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
