# Generated by Django 2.0.2 on 2018-03-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionpage', '0017_auto_20180321_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='is_upvoted',
            field=models.IntegerField(),
        ),
    ]
