# Generated by Django 2.0.2 on 2018-02-20 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionpage', '0006_auto_20180219_2104'),
        ('userpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
